services:
  pg-database:
    image: bitnami/postgresql
    container_name: pg-database 
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=sistema_nt